### ISSUE TITLE
Installing Procedure

### ISSUE THREAD

**Issue by GodOfConquest** [fake-name/wlnupdates#1]
Okay so how to install it? I'm also an budding python learner. I want to test out my skills on it. So how to install it? Tell me the procedure

**Comment by fake-name** [comment]
There isn't really a "procedure" per se.

Basically, you set up a virtualenv, install the needed dependencies listed in `requirements.txt`, and then just run `run.py`. 

This should /probably/ be mostly automated by the `build-venv.sh` and `upgrade_db.sh` scripts, but I'm not totally confident that the Database will bootstrap properly.

Oh, you also need a local postgres instance and (for the RSS stuff) a active MangaCMS instance, and a RabbitMQ instance that's accessible from the internet for mediating between the two.The configuration for those is in a file not in the repo (it's just passwords in a text file, basically).
It should be pretty simple to figure out, the settings are all copied across into `config.py` at runtime.

**Comment by GodOfConquest** [comment]
Okay, So what OS you personally use to run wlnupdates, mangacms?
And which one you recommend between CentOS or Ubuntu?

**Comment by fake-name** [comment]
I basically use Ubuntu for everything.
