### ISSUE TITLE
[API] Request for general API improvements

### ISSUE THREAD

**Issue by Cyroxin** [fake-name/wlnupdates#29]
Hello! 

I've been testing out the API you've provided and it is great. There are some things that could be improved though. I hope you continue developing this further!

1. **General simplification of the API.** Some "mode" parameters are not very well named.
- get-series-id =>get-series-data
- get-group-id  => get-group-data

2. **get-[type] modes should have their prefix parameter replaced with filter parameter.** Instead of one character filtering, multiple characters should be allowed at once. I believe filtering is currently done by finding the first letter of an item's name. Instead of this, the search should find items that have the query string in any position of the item's name. Renaming the offset parameter to page would also prove to simplify the API.

3. **Removal of genres and tags that contain less than 5 items.** There seems to be some novels with multiple genres combined as one. Example: "action-fantasy-comedy", I am guessing that this is a data extraction mistake. Filtering these mistakes out could be done by hiding genres that have less than 5 items from the API via a preference bool (HideIncompleteAttributes=included or HideItemsSmall=excluded). My recommendation is to create a options parameter on all api modes such as ( 'options': { 'HideIncompleteAttributes':'include', 'HideDebugParameter':'include'} )

4. **enumerate-tags mode, could be removed by abolishing the 50 item limitation from get-tags.** It is fine to have the option of limiting api results to only one page, however, most use cases require the full tags list. Enabling the possibillity of requesting the full tags list, would reduce the amount of data transferred. One request is much more efficient than many little ones.

5. **Improved searching**. "search-advanced" -searches are currently done by providing tag names. It would be easier in the long run if you were to allow an id to be used in the searches. This would allow searching for a translation group and a tag at the same time, as some translation groups have spaces in their name. This could be extended into including artist id's and publisher id's.

6. **Empty string checking in mode search-title.** => {"mode":"search-title","title":""}

> <h1>An unexpected error has occurred</h1>
>     <p>The administrator has been notified. Sorry for the inconvenience!</p>
>     <p><a href="/index">Back</a></p>

7. **[Feature Request] Chapter extraction.** Extracting the text from a chapter would provide offline reading capabilities for end-users. An easy solution would be to extract this data from a site that has already crawled through indevidual translation groups.  

8. **advanced-search potentially showing wrong items.** For some reason, advanced-search results do not exclude royalroad releases with the translated parameter set to excluded regardless of other parameters (such as Original English Language) included or excluded.

9. **get-series-id data reduction.** Removing unnecessary data elements will improve bandwidth limitations on low-end devices. For an example, there are duplicate return items.
* Chapter data
 ```
"latest": {
  "chp": 0.0, 
  "frg": 0.0, 
  "vol": 18.0 }
```
```
"latest_chapter": null, 
"latest_fragment": null, 
"latest_str": "vol. 18.0", 
"latest_volume": 18.0,
```
```

"progress":{
"chp": 0.0, 
"frg": 0.0, 
"vol": 18.0 } 
```
* Rating
```
"rating": {
  "avg": 6.0, 
  "num": 4, 
  "user": -1 }
```
`"rating_count": 4, `

Regards,
Cyroxin

**Comment by fake-name** [comment]
A bunch of good points. Some responses I can thin of currently:

> [Feature Request] Chapter extraction. Extracting the text from a chapter would provide offline reading capabilities for end-users. An easy solution would be to extract this data from a site that has already crawled through indevidual translation groups.

I actually already do this pretty comprehensively, see my [ReadableWebProxy](https://github.com/fake-name/ReadableWebProxy) project. 

However, actually re-hosting content is a horrible legal ball-of-issues I'm not interested in touching, so I'm not (and cannot) hosting the project publicly. 

> get-series-id data reduction. Removing unnecessary data elements will improve bandwidth limitations on low-end devices. For an example, there are duplicate return items.

It's maybe 20 bytes. Even if someone's on a 300 baud connection, that's what, 2/3 of a second? Also, the data you're describing isn't actually duplicate. 

```
"rating": {
  "avg": 6.0,      < This is the actual average rating
  "num": 4,       < This is how many people's ratings were used to generate that average
  "user": -1 }     < This is the current user's rating (if any, -1 indicates the user hasn't rated the series)
```

I can't see a way to reduce the parameters there. I guess I could exclude the 'user' parameter if the user hasn't rated the item, but that'd save maybe 9 bytes, and considering the HTTPs overhead, worrying about it is kind of nuts.

Most of the duplication are because the API basically exposes the data structures the site-itself uses to build the HTML pages. Basically, all the routes have an associated database function, the results of which are then passed through to the templating engine (jinja2, in this case). This is also the reason for the separate API methods - the pages have separate routes.

A lot of the other stuff is also the underlying storage backing leaking through the interface, though you're right about renaming things (or at least adding aliases). The `series-id` things are because the parameter you pass is actually the primary key for the relevant table, which is [actually named `id`](https://github.com/fake-name/wlnupdates/blob/master/app/models.py#L35). 

> Removal of genres and tags that contain less than 5 items. There seems to be some novels with multiple genres combined as one. Example: "action-fantasy-comedy", I am guessing that this is a data extraction mistake. Filtering these mistakes out could be done by hiding genres that have less than 5 items from the API via a preference bool (HideIncompleteAttributes=included or HideItemsSmall=excluded). My recommendation is to create a options parameter on all api modes such as ( 'options': { 'HideIncompleteAttributes':'include', 'HideDebugParameter':'include'} )

Yeah, this is a good idea. The data extraction stuff is definitely a bug, and limiting by tag-count is also a good idea. 

> enumerate-tags mode, could be removed by abolishing the 50 item limitation from get-tags. It is fine to have the option of limiting api results to only one page, however, most use cases require the full tags list. Enabling the possibillity of requesting the full tags list, would reduce the amount of data transferred. One request is much more efficient than many little ones.

The pagination here is basically because this is just exposing the exact same call used for the `/tags/` view. I have a materialized view for common tags internally already, I should just expose that.

> advanced-search potentially showing wrong items. For some reason, advanced-search results do not exclude royalroad releases with the translated parameter set to excluded regardless of other parameters (such as Original English Language) included or excluded.

Ooooh, that's legit a bug. The whole advanced search is kinda a hodgepoge anyways (JSON in a GET request!).


> Improved searching. "search-advanced" -searches are currently done by providing tag names. It would be easier in the long run if you were to allow an id to be used in the searches. This would allow searching for a translation group and a tag at the same time, as some translation groups have spaces in their name. This could be extended into including artist id's and publisher id's.

I don't actually remember why I implemented this the way it is. It's kind of crappy.

More later

**Comment by fake-name** [comment]
Todo:

 - [ ] 1. **General simplification of the API.**
 - [ ] 2. **get-[type] modes should have their prefix parameter replaced with filter parameter.** 
 - [ ] 3. **Removal of genres and tags that contain less than 5 items.**
 - [ ] 4. **enumerate-tags mode, could be removed by abolishing the 50 item limitation from get-tags.** 
 - [ ] 5. **Improved searching**. 
 - [ ] 6. **Empty string checking in mode search-title.** 
 - [ ] 8. **advanced-search potentially showing wrong items.** 
 
Rejected:
 - ~~[ ] 7. **[Feature Request] Chapter extraction.**~
 - ~~[ ] 9. **get-series-id data reduction.**~

**Comment by fake-name** [comment]
> advanced-search potentially showing wrong items. For some reason, advanced-search results do not exclude royalroad releases with the translated parameter set to excluded regardless of other parameters (such as Original English Language) included or excluded.

This appears to work for me. How are you testing this?

The following test script returns a null-set:

```

	post = {
		'mode'   : 'search-advanced',
		'series-type'  : {'Translated' : 'included'},
		'tag-category' : {
			'litrpg' : 'included',
			},
		'sort-mode' : "update",
		'chapter-limits' : [40, 0],
	}
	print("Request: ", post)
	pg = wg.getpage("http://127.0.0.1:5000/api", postJson=post)
	print(pg)
```
See https://github.com/fake-name/wlnupdates/blob/fd357650c471594fa0057c365f5f0e4af24a8ab9/test/api_poke.py#L90-L101

**Comment by Cyroxin** [comment]
Hello @fake-name ,
Glad to hear a quick response. I was actually worried that you might've felt as if the api wasn't being used and thus quit maintaining it. The API seems to be going forward very well. After these changes, it would be good to start documenting the api-docs a little more to instruct those who may not be following github. I'll see if I can dig out some more issues and potential improvements, but don't get your hopes up. 😛 

> 
> >     get-series-id data reduction. Removing unnecessary data elements will improve bandwidth limitations on low-end devices. For an example, there are duplicate return items.
> 
> It's maybe 50 bytes. Even if someone's on a 300 baud connection, that's what, a second?

The amount of unnecessary data is around 150 bytes, it is very small compared to the total size of the data sent by the api, which is a little over 20,000 bytes, that is true. Now that I think about it, the actual issue is not the 150 bytes, but it is a part of a larger scheme of issues.

If we were to create a list of novels for a user, they would want to see a cover image with the novel name. We would need to do this around 20-50 times depending on the screen size and this is without allowing the user to scroll down. Scrolling down means that we will have to load more items in the background using the api, the novels loaded in the background are also not guaranteed to be shown to the user.

50 novels * 20,000 bytes = 1MB (rounded)

My suggestion is to use the earlier mentioned "options" parameter to allow the developer to minimise the amount of data sent through. Looking at this, if we were to only receive the name of the novel and the cover image, that would be roughly 2000 bytes. That would be a 10x improvement on bandwidth. Now the 150 bytes is no longer that small, considering that 50 of them is already 7500 bytes, which is around 3-4 list items. However, if you are unable to implement this then that is completely fine as well.



>     advanced-search potentially showing wrong items. For some reason, advanced-search results do not exclude royalroad releases with the translated parameter set to excluded regardless of other parameters (such as Original English Language) included or excluded.
> 
> This appears to work for me. How are you testing this?

This appears to have been my bad, It seems that I was using the mode "search-title" instead of "search-advanced" with the parameters:

`{"mode":"search-title","title":"Test","series-type":{"Translated" : "included","Original English Language" : "excluded"},"sort-mode":"chapter","chapter-limits":[40,0]}`

As you said, merging the search modes seems to be a good idea. 

> 4. enumerate-tags mode, could be removed by abolishing the 50 item limitation from get-tags.
> I went the other way, and removed the get-tags call in d3962c1

I actually preferred the simplified mode name of get-tags, but that is fine. Do note that the other get-[?] modes currently send page results and they do not seem to have any enumerate mode variants.

**Comment by GPierre-Antoine** [comment]
Hey I borrow this thread to ask a quick question regarding the API, I don't find how to make a curl request to the api, could you give me direction please ?

For instance with the example above :

`$ curl -X POST -H 'Content-Type:Application/json' -d "{ 'mode'   : 'search-advanced',  'series-type'  : {'Translated' : 'included'}, 'tag-category' : { 'litrpg' : 'included', }, 'sort-mode' : 'update', 'chapter-limits' : [40, 0], }" https://wlnupdates.com/api`

yields a 400 bad request. Any idea ?

**Comment by fake-name** [comment]
Hmm, I'm not sure, I haven't actually thought about curl much.

**Comment by fake-name** [comment]
FWIW, @Cyroxin, the reason this hasn't moved in about a week is because I need to rewrite how the tagging system works pretty much entirely, since right now it has major performance issues I've been trying to ignore for a while.

**Comment by Cyroxin** [comment]
Thank you for your response @fake-name, I look forward to seeing how the API develops. I've halted my project till the rework on the API is finished. Feel free to close this issue, unless you'll be using it to show progress of this. Good luck with your projects!

Regards,
Cyroxin

**Comment by fake-name** [comment]
@Cyroxin  - I should have this done within this week, I hope.

**Comment by fake-name** [comment]
https://github.com/fake-name/wlnupdates/commit/5188a772fff0d703266191b45bc34cad0084b204 implements a set of additional methods for getting listings, in addition to the `get-nnn`. Functionally, it is identical, but you can now do a request with `{'mode' : 'get', 'data-type' : 'nnn'} for any of the normal sequential data-types.

**Comment by fake-name** [comment]
I think this should be more-or-less finished by https://github.com/fake-name/wlnupdates/commit/4230270318dd9dce9d73d3d63f1eddfbfa8a194a

I'd still like to make some of the "dumb" browsing modes a bit less useless.

Also, I can probably remove the pagination limits without too much issue.

The docs should be updated as well (though I've probably forgotten stuff).

**Comment by fake-name** [comment]
70a623f4619cdf0213fe2aef3f2fafa823bbe6a8 Should fix the garbage genres issue, at least temporarily.

It's manually maintained, but the proper solution is to figure out what the source of the bad genres is, and fix it there.
