### ISSUE TITLE
new login impossible

### ISSUE THREAD

**Issue by sebbu2** [fake-name/wlnupdates#341]
I'm still connected on the native browser on my tablet, but whenever i try to connect from a different browser (or a different device), i get the following error :

An unexpected error has occurred

The administrator has been notified. Sorry for the inconvenience!

If this continues to occur, please file an issue on the github issue tracker.Please include what you were doing when you ran into the issue.

Back

If i refresh the page a few time, I then get a CSRF error until i go back to the login form and refresh it.
This error was the same before and after seeing the last news on the site.

**Comment by GH-Harry** [comment]
Having the same issue, trying to login and getting the same admin error message.

**Comment by fake-name** [comment]
Oh gosh, sorry about that. 

> The administrator has been notified. Sorry for the inconvenience!

Basically, that means I have a bug somewhere. I'll look at it when I get home later.

**Comment by fake-name** [comment]
Ok, it should work now. I've also flushed all non-verified accounts.

Also, wow, that was a *dumb* bug.

**Comment by sebbu2** [comment]
thx, it works now :)

**Comment by fake-name** [comment]
Wewt!
