### ISSUE TITLE
Login for existing account invalid

### ISSUE THREAD

**Issue by joberin** [fake-name/wlnupdates#348]
When attempting to log into an existing account I get the [Invalid salt] error message. An interesting point on this is that no matter what password I enter, that is over eight characters, will show [Invalid salt] even if the password is incorrect.
It does look like this could be an issue that is connected to my account for whatever reason as I have created a test account and I was able to log into the new account without issue.

I believe I verified the account so it should not have been purged or the like.

(Issue was originally reported via email and has continued.)

**Comment by fake-name** [comment]
I believe this was a occurrence of https://github.com/fake-name/wlnupdates/issues/4. I think it should be solved now, let me know if it continues to occur.

(Also, I'm not sure how I missed this issue, sorry about that!).

**Comment by joberin** [comment]
That's done it.

**Comment by fake-name** [comment]
Woot!
