### ISSUE TITLE
Receiving ' Please confirm your account first. ' banner when login in.

### ISSUE THREAD

**Issue by Wolfpup67** [fake-name/wlnupdates#378]
I just recently created an account on the site and when i go to log in I get the above notice. I have checked my email there is no confirmation email. If i try to redo the account it now says the user name is taken. here is a screen shot after logging in.
![Screenshot_2019-04-06_17-21-23](https://user-images.githubusercontent.com/8302307/55675444-ad726100-5890-11e9-8acb-2a6bda40ef02.png)

**Comment by fake-name** [comment]
The account is registered, but not yet activated. 

Can you check your spam folder? I don't have a "proper" MTA, so I pretty regularly get confirmation e-mails flagged as spam.

**Comment by Wolfpup67** [comment]
I have checked there and there is no email there at all.

**Comment by fake-name** [comment]
Ok, yeah, my mail send account was pooping itself for some reason I don't really understand.

Anyways, I switched it back to gmail, and was able to register a test-account without issue (though the mail does end up in my spam filter.  Gah).

Anyways, I'll drop all users that are unverified. You should then be able to re-register with your username.
