### ISSUE TITLE
Received no WLN email

### ISSUE THREAD

**Issue by whatsawhizzer** [fake-name/wlnupdates#390]
Received no WLN email while trying to sign up my whatsawhizzer@gmail.com account.

**Comment by MiraiSaesang** [comment]
Hello, I signed up for an account, but did not receive an the verification email, so cannot use the account, my username is : MiraiSaesang

Thank you!

**Comment by fake-name** [comment]
The confirmation e-mail system got blocked again. Dammit.

I need to figure out a reliable way to send e-mails, because this is freaking annoying.

**Comment by fake-name** [comment]
I manually verified your accounts for the moment. Sorry I've been slow about this.

**Comment by whatsawhizzer** [comment]
Thanks for the update. Since I got your attention, I was also hoping you could fix something for me. Some of my novels got duplicated. "World of Women" and "The World of Women" Are the same novel. So is "Power of Creation" and "The Power of Creation". The reason there is a discrepancy is because I was fast and loose on the "the", but ultimately it's because someone pirated my novels and put them on Qidian without my permission, dropping the "the" themselves and then creating two books. If the information could be merged together, I'd appreciate it. You might as well drop the "the" and form to the name without it.

**Comment by fake-name** [comment]
@whatsawhizzer - Yeah, no problem. The extremely automated nature of the site causes lots of duplicates, it's quite annoying.

 - "World of Women" 
 - "The World of Women" 

These were already merged. 

 - "Power of Creation" 
 - "The Power of Creation"

Done. 

One thing I'd like to ask is if you can mark posts that are patreon only in some way, so I can filter them from the generated chapters. Right now I'm doing some horrible hackery based on length of post + some magic strings. Something like a post tag that is only applied to locked chapters would be nice, and not rely on brittle string messyness.

**Comment by nonynonynony** [comment]
Same problem, no confirmation e-mail sent. Username: nonnonnon

**Comment by fake-name** [comment]
@nonynonynony - Yeah, google gets really cranky about accounts that only ever send email, even if they're explicitly solicited. They blocked the account I was use for sending registration mails, and it's been bouncing for a while.

Anyways, I finally broke down and set up a proper mail account that's hosted on the same domain. 

In any case, I manually activated your account. You should be able to log in now.

**Comment by nonynonynony** [comment]
Thanks.
