### ISSUE TITLE
Invalid Salt

### ISSUE THREAD

**Issue by smmalmansoori** [fake-name/wlnupdates#4]
I get an [Invalid salt] message when trying to login after creating an account and confirming the email.

**Comment by fake-name** [comment]
Well, that's annoying. I did recently update the session management stuff, let me see if that's the source of the issue.

**Comment by fake-name** [comment]
Ok, so one of the libraries is now broken. Let me see if I can figure out what happened,

**Comment by fake-name** [comment]
`Flask-bcrypt` started doing type conversions in a way that broke authentication everywhere, apparently. It's fixed now, in any event.

**Comment by smmalmansoori** [comment]
This issue is back again

**Comment by fake-name** [comment]
Can you tell me the username you're seeing the issue from? 

Alternatively, e-mail it to me at admin@wlnupdates.com, if you don't want it to be public.

**Comment by smmalmansoori** [comment]
smmalmansoori

**Comment by smmalmansoori** [comment]
Don't know if you did something on your side yet but now its working again

**Comment by fake-name** [comment]
I've been futzing with the auth packages trying to figure out what's going on.

There's some fiddly install-order-dependent things going on, not sure what.

**Comment by smmalmansoori** [comment]
Don't know how much this would help but maybe it would help by simplifying your dependencies for example:
* remove flask-security (last release on on Jun 14, 2017) and use flask-login directly
* remove flask-bcrypt and use the [generate_password_hash](https://werkzeug.palletsprojects.com/en/0.15.x/utils/?highlight=generate_password_hash#werkzeug.security.generate_password_hash)

**Comment by fake-name** [comment]
Yeah, I mean, mostly my concern is breaking the currently functional (?) auth. 

I would hope this sort of thing would be stable, but apparently that's too much to ask.

**Comment by smmalmansoori** [comment]
You'll need to rehash with the new method on successful login this way the old method will be eventually phased out
