### ISSUE TITLE
registration link 

### ISSUE THREAD

**Issue by otwentyfirst** [fake-name/wlnupdates#401]
I guess I waited too long because my link said it was invalid. 
username: otwentyfirst
email: otwentyfirst@gmail.com

**Comment by fake-name** [comment]
I manually verified your account. You should now be able to log in.

**Comment by Hemiko-nyu** [comment]
I guess I waited too long because my link said it was invalid.
username: Hemiko
email:sheilacori124@gmail.com

**Comment by fake-name** [comment]
@Hemiko-nyu - You should be enabled now. 

FWIW, your username is `Hemiku`, not `Hemiko`. If that's a typo, I can fix it.
