### ISSUE TITLE
Understanding how to get API results.

### ISSUE THREAD

**Issue by fake-name** [fake-name/wlnupdates#45]
Received via e-mail:

> I want to have to have the rss flux for every new chapters.
I used https://www.wlnupdates.com/api/get-releases
but didn't get anything, is it normal ?

**Comment by fake-name** [comment]
That's not how the API works. 

**ALL** api routes have the same, end point, https://www.wlnupdates.com/api. The API function is controlled by the POSTed parameters.

In this case, `curl -X POST -H 'Content-Type:Application/json' -d "{ \"mode\" : \"get-feeds\" }" https://www.wlnupdates.com/api` would be the way to get the *rss feeds*. 

If you want parsed releases, you'd do something like `curl -X POST -H 'Content-Type:Application/json' -d "{ \"mode\" : \"get-releases\" }" https://www.wlnupdates.com/api`

**Comment by Kenji94** [comment]
Hi,
Sorry for the late answer, I got a lot of work recently.
It's ok it's working now :)

By the way, I really don't understand the difference between get-feeds vs get-releases.
Ok the format is not the same, but they don't have the same chapter releases.
I'm finding gravity tales on one but royalRoadL on the other

**Comment by Kenji94** [comment]
You mean rss feed vs you parse yourself some websites ?

**Comment by fake-name** [comment]
Yes. 

`get-feeds` is basically just aggregated RSS content. It contains both release info, and whatever else the various sites post.

`get-releases` gets things that the scraper backend thinks are *actually* releases, and contains structured data (numeric chapter/volume/part) information where possible.

**Comment by Kenji94** [comment]
Thank your for your fast reply!
It's a shame the scrapping of website is not legal otherwise I would have used get-release too :(

Le 28 mars 2018 00:52, Connor Wolf <notifications@github.com> a écrit :

Yes.

get-feeds is basically just aggregated RSS content. It contains both release info, and whatever else the various sites post.

get-releases gets things that the scraper backend thinks are actually releases, and contains structured data (numeric chapter/volume/part) information where possible.

**Comment by fake-name** [comment]
> It's a shame the scrapping of website is not legal otherwise I would have used get-release too

Uh.... what?

**Comment by Kenji94** [comment]
I'm pretty sure in the term of use and policy privacy of most of the websites, there is a clause : no scrapping is allowed

**Comment by fake-name** [comment]
What does that have to do with the wlnupdates.com api whatsoever?

**Comment by Kenji94** [comment]
For example, if I'm showing royalRoadL new chapters on an app, they can go against me as I don't have their permission

**Comment by fake-name** [comment]
Well, considering RoyalRoadL are *literally* adding API end-points for me so I can get releases more easily, I think they're fine with it?

**Comment by Kenji94** [comment]
Nice!
So you contacted them and they gave you their api end-points ?

**Comment by fake-name** [comment]
No, the actually contacted me and asked if I could move away from plain scraping.

Realistically, if you have a web site *on the internet*, you are going to get hit by bots. People who think otherwise are idiots.

**Comment by Kenji94** [comment]
Ok.
One last question :)
On the mode get-feeds, why there is not a field bookName ?
The only rule I have found to find it is, if tags.size==1, it is the bookName

**Comment by fake-name** [comment]
The `get-feeds` interface returns aggregated rss feeds. They are not associated with series.

`get-releases` is the `get-feeds` data that's been run through the feed parser system.
