### ISSUE TITLE
Preferred Title

### ISSUE THREAD

**Issue by smmalmansoori** [fake-name/wlnupdates#5]
Ability for logged in user to choose preferred novel title. I think this is a huge usability win.

Example:
I have "Mang Huang Ji" in my watched items. I would like to go to the novel details page, scroll down to alternative names, and choose "Desolate Era" as my preferred title. From then on it will be listed as "Desolate Era" in my watched list.

**Comment by fake-name** [comment]
That's an interesting idea, but I don't see how it could be implemented in a way that's not complicated in terms of the UI.

Let me think about how it'd be implementable.

**Comment by smmalmansoori** [comment]
How about radio buttons in "Alternative Names"?

**Comment by fake-name** [comment]
Yeah, but the idea is to (hopefully) not confuse people who don't know what it does.

**Comment by fake-name** [comment]
Backend work for this is done, but I haven't figured out how to make the UI components for managing the settings not confusing or requiring of some inline documentation. I'd still like to make it work, though.

**Comment by smmalmansoori** [comment]
I think having it in "Alternative Names" will spare you the inline documentation as the intent is almost self evident.

![screenshot from 2016-08-13 14-29-38](https://cloud.githubusercontent.com/assets/3144938/17642729/a471688a-6162-11e6-9976-318afbec1cbc.png)
.

**Comment by fake-name** [comment]
Yeah, mostly I have to just poke around and try stuff.

**Comment by fake-name** [comment]
Now implemented.

Note that this only causes the series to be renamed in your watch list, and when viewing the series info page. The default naming is still used when browsing series, mostly because I haven't routed the watch list information through to those views (and I probably won't do so, because it'd force more DB queries for every view that lists any series names).
