### ISSUE TITLE
[API] Post Request Bug Fixes

### ISSUE THREAD

**Issue by Cyroxin** [fake-name/wlnupdates#59]
Heyo!

These new features are very nice. I've been quite busy, but I'm finally able to check out the new API additions. Though I ran into some issues along the way. Some requests seem to work fine when using the docs and some just utterly fail and lose their will to live. Here is a small list I've tried. 

PS. By "Internal Error", I mean that the post requests fails with an error code of 500 and sends a default webpage with HTML explaining that the issue has been noted. 

---

1. `search-advanced` with only a title parameter. It seems that if you add a tags request to it, it works. This could be an intentional error and it is not really an issue, as if a user really does request this, then the issue can be manually repaired by using the title search api function instead.

<details>
<summary>Click to see post request </summary>

---

**ERROR POST RAW:** `"{\"mode\":\"search-advanced\", \"title-search-text\":\"Hola\"}"`
**ERROR POST PURE:** `{"mode":"search-advanced","title-search-text":"Hola"}`

**WORKING POST  RAW:** `"{\"mode\":\"search-advanced\", \"tag-category\" : { \"ability-steal\" : \"included\", \"virtual-reality\" : \"excluded\" }, \"title-search-text\":\"Hola\"}"`
**WORKING POST  PURE:** `{"mode":"search-advanced","tag-category" : {"ability-steal" : "included", "virtual-reality" : "excluded"}, "title-search-text":"Hola"}`

---

</details>

2. `search-advanced` unknown internal server error. This is an odd one, I tried moving the "include-results" around, but with no luck. Though it seems like adding `title-search-text` with some random character or word fixes it? Does magic exist after all?

<details>
<summary>Click to see post request </summary>

---

**ERROR POST RAW:** `"{\"mode\":\"search-advanced\", \"tag-category\" : { \"ability-steal\" : \"included\", \"virtual-reality\" : \"excluded\" },\"include-results\": [\"covers\"] }" `
**ERROR POST PURE:** `{"mode":"search-advanced","tag-category" : {"ability-steal" : "included", "virtual-reality" : "excluded"}, "include-results":["covers"]}"`

---

</details>

3. `search-advanced` **title-search-text** requires parameter validity checks. Empty input or input with only a space causes an internal server error.

4. `get-[?]` and `enumerate-[?]` internal error on genres and tags. I started by testing `enumerate-[?]` -modes, which apparently you prefer over the existing `get-[?]` -modes, though I have had some issues with both. I've tested all of the requests and the results are as follows, those not mentioned are working.

`{"mode": "enumerate-genres"}` => Internal Error
`{"mode": "enumerate-tags"}` => Internal Error
`{"mode": "get-genres"}` => Works, wasn't this depreciated?
`{"mode": "get-tags"}` => API Error, I assume this is just a removed mode and not an error.

The other `get-[?]` -modes seem to work. I am unsure if `get-[?] ` -modes are depreciated or not, as some of them do not have any `enumerate-[?]` alternatives to use.

---

Thank you for maintaining this API, if you have a method of contact such as discord, do let me know. 

Regards,
Cyroxin

**Comment by fake-name** [comment]
Wow, that's embarrassing.

**Comment by fake-name** [comment]
> The other get-[?] -modes seem to work. I am unsure if get-[?] -modes are depreciated or not, as some of them do not have any enumerate-[?] alternatives to use.

The `get-[?]` aren't likely to go anywhere. Basically, most of the API is just a more convenient way to access existing site endpoints. Specifically, the `get-[?]` tags are very thin wrappers around things like the websites `www.wlnupdates.com/authors/`, `www.wlnupdates.com/artists/` etc internal queries.

The `enumerate-[?]` endpoints exist mostly because just reusing the html end-points works poorly for certain things.

**Comment by fake-name** [comment]
> search-advanced title-search-text requires parameter validity checks. Empty input or input with only a space causes an internal server error.

I'm confused. I'm trying a request:

```
Request:  {'mode': 'search-advanced', 'title-search-text': ''}
```
And it returns:
```
Response:
{
  "error": true,
  "message": "Insufficent filter parameters!",
  "reload": true
}
```

Searching for just a space (`" "`) seems to return every series on the server with more then one word in their name and throws a slow-query warning, so I think I'll add a 2 non-space char minimum to the search interface.

**Comment by fake-name** [comment]
Ok, the source of most of the issues was that if there was a release in the search return that didn't have any releases, it'd throw an error.

This was because the timestamp conversion wasn't handling the case where the timestamp was null, and it was throwing an exception. That was derptastic.

**Comment by fake-name** [comment]
Ok, changes are live, and my api-poke testing script seems to not be throwing any errors.
