### ISSUE TITLE
API returns trailing slash on cover image URLs

### ISSUE THREAD

**Issue by JacenBoy** [fake-name/wlnupdates#665]
When requesting covers from the "search-advanced" search mode in the API, the URLs include a trailing slash. I believe this is causing the server to try to serve a directory instead of the image, which creates a 404 error. Removing the trailing slash returns the image correctly.

**Comment by fake-name** [comment]
Yep, this was a super dumb bug for formatting the cover URL. Thanks for pointing it out!

FWIW, there is just no route handler for `/cover-img/{id}/`, which is why it was 404'ing.

**Comment by fake-name** [comment]
Patch should be live.

Let me know if you find further issues! I'd be surprised if this is the only silly thing I missed. Thanks!
