### ISSUE TITLE
Retrieving list of watched series from the API

### ISSUE THREAD

**Issue by sebbu2** [fake-name/wlnupdates#684]
The mode: get-watches seems to exists, but isn't yet implemented.

**Comment by fake-name** [comment]
Somehow I missed this. Sorry!

Anyways, this is now implemented and documented in f2cd241ddb64f37bc51e98c449660d75aca366e2.

See https://github.com/fake-name/wlnupdates/blob/f2cd241ddb64f37bc51e98c449660d75aca366e2/app/templates/api-docs.md#get-watches

I have also implemented API based authentication, see https://github.com/fake-name/wlnupdates/blob/f2cd241ddb64f37bc51e98c449660d75aca366e2/app/templates/api-docs.md#logging-in-do-login.
