### ISSUE TITLE
[Question] Getting novel updates in Python

### ISSUE THREAD

**Issue by AlphaNeo513** [fake-name/wlnupdates#688]
Hello, is there a way to get novel updates in real time? For example if I want to get notified when a novel release I can subscribe to it and get a reponse everytime it updates using python.

**Comment by fake-name** [comment]
Hmm, unfortunately I don't have any mechanism for pub/sub, or the message broker infrastructure to make something like that public. 

Really, I don't think that the message volume is sufficient for that in the first place. The site gets at peak perhaps 50 releases an hour. That's not really real-time at it's core.

You can get 90% of the way there via the reading list interface + periodic polling, though you'd need to track state changes in the latest available chapter client side. Basically query your reading list every 5 minutes or so, and if the latest chapter number has changed, there's been an update.   
Alternatively, you could just fully use the reading list system, which internally tracks where you've read to, and whether there's any new chapters available.

**Comment by AlphaNeo513** [comment]
Guess I'll do that then. Thanks for answering!
