### ISSUE TITLE
How to Authenticate in the API?

### ISSUE THREAD

**Issue by GrayTsar** [fake-name/wlnupdates#690]
Sometimes my app hits the api rate limit.

I just cant figure out how to authenticate.

I tried out the basic auth with postman. Tested it with get-watches and i get in the message that calls can only be made with logged in user.

**Comment by fake-name** [comment]
I've implemented a API login endpoint.

See  https://github.com/fake-name/wlnupdates/blob/master/app/templates/api-docs.md#logging-in-do-login.
