### ISSUE TITLE
Request: OAuth2 for Authentication

### ISSUE THREAD

**Issue by GrayTsar** [fake-name/wlnupdates#692]
Login works with no problem. Tests with postman are also good. 

The problem is that with mobile applications, a constant connection is not guaranteed. Turning off the screen would be enough to end the connection.
It would be great if you could implement OAuth2 for token authentication.

**Comment by fake-name** [comment]
As long as you hold onto the cookie set on login (and don't specify `'remember-me': False` as a parameter), you should be good to stay authenticated for I think 6 months.

> Turning off the screen would be enough to end the connection.

Authentication isn't connection based. Frankly, I don't think I even *support* persistent connections. If they work, it's probably nginx (which I use as a caching proxy) terminating them.

**Comment by GrayTsar** [comment]
Ah, it is cookie based.

Got it working for me now too. 👍
