### ISSUE TITLE
Some novels with wrong latest chapters

### ISSUE THREAD

**Issue by smmalmansoori** [fake-name/wlnupdates#7]
[I'm Really a Superstar](https://www.wlnupdates.com/series-id/35954/)
The latest release c478 actually belongs to True Martial World.

[Panlong](https://www.wlnupdates.com/series-id/1274/)
The latest release v30 c32 actually points to v20 c32. The post on WuxiaWorld was mistakenly titled "New CD Chapter Release! Book 30, Chapter 32" but if you follow the link in the post you will be directed to v20 c32.

[The Great Ruler](https://www.wlnupdates.com/series-id/33415/)
The latest release c19930 is actually wrongly parsed from the translator's name jn19930.

**Comment by fake-name** [comment]
> I'm Really a Superstar

Gravity tales mis-tagged their release. Hah.


> Panlong

Wuxiaworld has typos in their series a *lot*. Also, they seem to have /still/ not fixed the release name. Sigh.

> The Great Ruler

Well, that's an annoying translator name.

**Comment by smmalmansoori** [comment]
Thanks!
