### ISSUE TITLE
Found duplicates of deleted series

### ISSUE THREAD

**Issue by arrivedercia** [fake-name/wlnupdates#754]
https://www.wlnupdates.com/series-id/137473/call-of-tardigrade-takes-27-chapters-to-become-an-isekai
https://www.wlnupdates.com/series-id/128497/call-of-tardigrade
https://www.wlnupdates.com/series-id/137392/call-of-tardigrade-revised-amp-continued
https://www.wlnupdates.com/series-id/137551/call-of-tardigrade-an-isekai-with-extra-steps
https://www.wlnupdates.com/series-id/136992/call-of-tardigrade-a-progression-sci-fi-fantasy
https://www.wlnupdates.com/series-id/120456/maths-vol-2-apollo-2-monday-saga
@ admin found more duplicates of an old series due to name changes, could you delete these as well, thank you!

**Comment by arrivedercia** [comment]
https://www.wlnupdates.com/series-id/130050/a-week-to-infinity
https://www.wlnupdates.com/series-id/134141/awti

**Comment by arrivedercia** [comment]
That should be all of them c:

**Comment by fake-name** [comment]
Done. 

Man, I think royalroad needs to limit how often people can change their series names. Ugh.
